import { NextResponse } from "next/server";

const spec = {
  openapi: "3.1.0",
  info: {
    title: "7Krave API",
    version: "1.0.0",
    description:
      "Versioned REST API shared by the Next.js storefront, ys-admin and the future mobile app. Auth: session cookie (web) or `Authorization: Bearer <token>` (mobile).",
  },
  servers: [{ url: "/api/v1" }],
  paths: {
    "/products": { get: { summary: "Search active products: q, category, price, shipping, rating, sort (no auth)" } },
    "/products/{slug}": { get: { summary: "Product detail: gallery, variants, specs, reviews, related (no auth)" } },
    "/products/{slug}/reviews": { get: { summary: "Paginated reviews (no auth)" }, post: { summary: "Review, verified buyers only (auth)" } },
    "/reviews/{id}/helpful": { post: { summary: "Toggle helpful vote (auth)" } },
    "/selling/products": { get: { summary: "My listings (seller)" }, post: { summary: "Create listing as draft (seller)" } },
    "/selling/products/{id}": {
      get: { summary: "Listing detail (seller)" },
      patch: { summary: "Edit listing + variants (seller)" },
      delete: { summary: "Delete listing without orders (seller)" },
    },
    "/selling/reviews/{id}": { patch: { summary: "Reply to a review (seller)" } },
    "/stores/{slug}": { get: { summary: "Store profile + products + follow state (no auth)" } },
    "/stores/{slug}/reviews": { get: { summary: "Store-wide reviews (no auth)" } },
    "/stores/{slug}/follow": { post: { summary: "Follow store (auth)" }, delete: { summary: "Unfollow (auth)" } },
    "/selling/store": { get: { summary: "My store profile(s) (seller)" }, patch: { summary: "Update store profile (seller)" } },
    "/selling/dashboard": { get: { summary: "Revenue, orders, rating, escrow KPIs (seller)" } },
    "/admin/stats": { get: { summary: "Dashboard KPIs (admin)" } },
    "/admin/vendors": { get: { summary: "List vendors, filter ?status= (admin)" } },
    "/admin/vendors/{id}": {
      get: { summary: "Vendor with analytics (admin)" },
      patch: { summary: "Approve / reject / suspend / commission (admin)" },
    },
    "/admin/products": { get: { summary: "List products (admin)" } },
    "/admin/products/{id}": { patch: { summary: "Takedown / restore product (admin)" } },
    "/admin/orders": { get: { summary: "List orders, filters ?status=&q= (admin)" } },
    "/admin/orders/{id}": { get: { summary: "Order with buyer + timeline (admin)" }, patch: { summary: "Transition order, tracking, notes (admin)" } },
    "/selling/orders": { get: { summary: "Orders with my items (seller)" } },
    "/selling/orders/{id}": { get: { summary: "Order detail, my lines (seller)" }, patch: { summary: "Ship / deliver (seller)" } },
    "/account/orders": { get: { summary: "My orders (auth)" } },
    "/account/orders/{number}": { get: { summary: "My order with timeline (auth)" } },
    "/admin/disputes": { get: { summary: "List disputes, filters ?status=&category= (admin)" } },
    "/admin/disputes/{id}": { get: { summary: "Dispute with escrow holds (admin)" }, patch: { summary: "Rule on dispute, auto-settles funds (admin)" } },
    "/admin/payouts": { get: { summary: "Payout ledger (admin)" } },
    "/admin/ops/run": { post: { summary: "Release escrow + auto-pay payouts (admin)" } },
    "/account/disputes": { get: { summary: "My disputes (auth)" }, post: { summary: "File a dispute, freezes escrow (auth)" } },
    "/account/disputes/{id}": { get: { summary: "My dispute thread (auth)" }, patch: { summary: "Buyer reply (auth)" } },
    "/selling/disputes": { get: { summary: "Disputes on my items (seller)" } },
    "/selling/disputes/{id}": { get: { summary: "Dispute thread (seller)" }, patch: { summary: "Seller reply (seller)" } },
    "/selling/payouts": { get: { summary: "My balance + payout history (seller)" } },
    "/admin/coupons": { get: { summary: "List coupons, filters ?active=&type=&q= (admin)" }, post: { summary: "Create coupon (admin)" } },
    "/admin/chat": { get: { summary: "Conversation metadata queue, ?reported=1 (admin)" } },
    "/admin/chat/{id}": { get: { summary: "Metadata + activity, never bodies (admin)" } },
    "/chat/conversations": { get: { summary: "My conversations (auth)" }, post: { summary: "Open order/inquiry chat (auth)" } },
    "/chat/conversations/{id}": { get: { summary: "Thread metadata + my envelope (auth)" }, patch: { summary: "block | unblock | report (auth)" } },
    "/chat/conversations/{id}/messages": { get: { summary: "Message feed (auth)" }, post: { summary: "Send message, screened + sealed (auth)" } },
    "/chat/conversations/{id}/read": { post: { summary: "Read receipt (auth)" } },
    "/chat/conversations/{id}/typing": { post: { summary: "Typing heartbeat (auth)" } },
    "/chat/uploads": { post: { summary: "Sealed image blob upload (auth)" } },
    "/chat/stream": { get: { summary: "SSE live thread events (auth)" } },
    "/admin/deals": { get: { summary: "List flash deals (admin)" }, post: { summary: "Schedule a deal (admin)" } },
    "/admin/deals/{id}": {
      get: { summary: "Deal detail (admin)" },
      patch: { summary: "Edit or end a deal (admin)" },
      delete: { summary: "Delete a non-live deal (admin)" },
    },
    "/deals": { get: { summary: "Live + scheduled deals (no auth)" } },
    "/account/wishlist": { get: { summary: "My wishlist (auth)" }, post: { summary: "Save item + price target (auth)" } },
    "/account/wishlist/{slug}": { delete: { summary: "Remove saved item (auth)" } },
    "/account/notifications": { get: { summary: "My inbox (auth)" }, patch: { summary: "Mark read (auth)" } },
    "/account/preferences": { get: { summary: "My email prefs (auth)" }, patch: { summary: "Opt out of lifecycle mail (auth)" } },
    "/account/cart": { post: { summary: "Mirror cart for recovery (auth)" } },
    "/admin/coupons/{id}": { get: { summary: "Coupon detail + redemptions (admin)" }, patch: { summary: "Update coupon (admin)" }, delete: { summary: "Delete coupon" } },
    "/coupons": { get: { summary: "Active public coupons (no auth)" } },
    "/coupons/validate": { post: { summary: "Quote a coupon against a basket (no auth)" } },
    "/checkout": { post: { summary: "Place an order, optional couponCode (auth)" } },
    "/admin/users": { get: { summary: "User directory, filters ?q=&role=&status= (admin)" } },
    "/admin/users/{id}": {
      get: { summary: "User profile + activity (admin)" },
      patch: { summary: "role | suspend | unsuspend | resetPassword | profile (admin)" },
      delete: { summary: "Delete account without history (admin)" },
    },
    "/account/profile": { patch: { summary: "Update my display name (auth)" } },
    "/account/password": { post: { summary: "Change my password (auth)" } },
    "/admin/api-tokens": {
      get: { summary: "List mobile API tokens" },
      post: { summary: "Mint a bearer token (raw token shown once)" },
    },
    "/admin/audit": { get: { summary: "Activity log, filters ?action=&entity=&actorId= (admin)" } },
    "/admin/settings": {
      get: { summary: "All site + system settings (admin)" },
      patch: { summary: "Partial per-group settings update (admin)" },
    },
    "/admin/uploads": {
      get: { summary: "Recent uploads (admin)" },
      post: { summary: "Upload an image, max 2MB (admin)" },
    },
    "/settings/public": { get: { summary: "Public brand + banner settings (no auth)" } },
    "/auth/register": { post: { summary: "Create a buyer account (public)" } },
    "/auth/become-seller": { post: { summary: "Open a store for the signed-in user" } },
  },
};

export async function GET() {
  return NextResponse.json(spec);
}
