/**
 * Sample test catalog (~100 listings). Honestly labeled fictional sample data
 * for evaluation — real-pattern brands, specs, variants and tags so search,
 * grouping, missions and the AI assistant can be exercised realistically.
 * Every row is written with source="sample" so it wipes cleanly before
 * production (`DELETE FROM "Product" WHERE source IS NOT NULL`).
 *
 * Conventions: price/compareAt in USD, specs as [key, value] tuples,
 * variant stock drives the assistant's stock/restock paths (a couple of
 * listings are fully out of stock on purpose).
 */

export type SampleVariant = { name: string; price?: number; stock: number };

export type SampleEntry = {
  slug: string;
  title: string;
  category: string;
  brand: string;
  tags: string[];
  price: number;
  compareAt?: number;
  badge?: string;
  variants?: SampleVariant[];
  specs: Array<[string, string]>;
  freeShipping?: boolean;
  trackStock?: boolean;
  stock?: number;
};

export const SAMPLE_PRODUCTS: SampleEntry[] = [
  // ------------------------------------------------------------- electronics
  {
    slug: "sample-airpods-pro-2",
    title: "Apple AirPods Pro (2nd Generation) with MagSafe Charging Case",
    category: "electronics",
    brand: "Apple",
    tags: ["audio", "commuting", "travel", "giftable"],
    price: 189.99,
    compareAt: 249.0,
    badge: "Hot",
    specs: [
      ["Chip", "Apple H2 headphone chip"],
      ["Noise control", "2x Active Noise Cancellation, Adaptive Transparency"],
      ["Battery", "Up to 6h buds, 30h with case"],
      ["Rating", "IP54 dust, sweat and water resistant"],
      ["Connectivity", "Bluetooth 5.3, MagSafe + USB-C charging"],
    ],
  },
  {
    slug: "sample-sony-wf1000xm5",
    title: "Sony WF-1000XM5 Noise Cancelling Wireless Earbuds",
    category: "electronics",
    brand: "Sony",
    tags: ["audio", "commuting", "giftable"],
    price: 228.0,
    compareAt: 299.99,
    specs: [
      ["Driver", "8.4mm Dynamic Driver X"],
      ["Noise control", "Industry-leading ANC, 3 mics per bud"],
      ["Battery", "8h buds, 24h with case, 3-min quick charge"],
      ["Codecs", "LDAC, AAC, SBC"],
    ],
  },
  {
    slug: "sample-soundcore-p30i",
    title: "Soundcore P30i by Anker Noise Cancelling Earbuds",
    category: "electronics",
    brand: "Soundcore",
    tags: ["audio", "commuting", "giftable"],
    price: 24.99,
    compareAt: 39.99,
    badge: "Choice",
    specs: [
      ["Driver", "10mm composite drivers"],
      ["Noise control", "Hybrid ANC reduces 42dB"],
      ["Battery", "10h buds, 45h with case"],
      ["Rating", "IPX5 water resistant"],
    ],
  },
  {
    slug: "sample-bose-qc-headphones",
    title: "Bose QuietComfort Wireless Noise Cancelling Headphones",
    category: "electronics",
    brand: "Bose",
    tags: ["audio", "travel", "office", "giftable"],
    price: 319.0,
    compareAt: 349.0,
    specs: [
      ["Noise control", "Legendary ANC with Quiet/Aware modes"],
      ["Battery", "Up to 24h per charge"],
      ["Microphones", "Noise-rejecting mic system for calls"],
      ["Multipoint", "Connect two devices at once"],
    ],
  },
  {
    slug: "sample-sony-wh1000xm5",
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    category: "electronics",
    brand: "Sony",
    tags: ["audio", "travel", "office"],
    price: 328.0,
    compareAt: 399.99,
    specs: [
      ["Processor", "2 processors, 8 mics, Auto NC Optimizer"],
      ["Battery", "30h with quick charge (3 min = 3h)"],
      ["Design", "Lightweight 250g, soft-fit leather"],
      ["Codecs", "LDAC Hi-Res Audio"],
    ],
  },
  {
    slug: "sample-jbl-flip-6",
    title: "JBL Flip 6 Portable Bluetooth Speaker Waterproof",
    category: "electronics",
    brand: "JBL",
    tags: ["audio", "outdoors", "camping", "giftable"],
    price: 89.95,
    compareAt: 129.95,
    badge: "Sale",
    variants: [
      { name: "Black", stock: 14 },
      { name: "Blue", stock: 9 },
      { name: "Red", stock: 0 },
    ],
    specs: [
      ["Output", "20W RMS, racetrack woofer + tweeter"],
      ["Battery", "12h playtime, USB-C charging"],
      ["Rating", "IP67 waterproof and dustproof"],
      ["PartyBoost", "Pair multiple speakers"],
    ],
  },
  {
    slug: "sample-apple-watch-se",
    title: "Apple Watch SE (2nd Gen) GPS 40mm Midnight",
    category: "electronics",
    brand: "Apple",
    tags: ["fitness", "outdoors", "giftable"],
    price: 189.0,
    compareAt: 249.0,
    variants: [
      { name: "Midnight 40mm", stock: 7 },
      { name: "Starlight 40mm", stock: 5 },
      { name: "Midnight 44mm", price: 219.0, stock: 4 },
    ],
    specs: [
      ["Chip", "S8 SiP, watchOS"],
      ["Sensors", "Heart rate, sleep stages, Crash Detection"],
      ["Water", "50m water resistant"],
      ["Battery", "Up to 18h, fast charging"],
    ],
  },
  {
    slug: "sample-pulsefit-band-2",
    title: "PulseFit Band 2 Fitness Tracker with Heart Rate and Sleep Monitor",
    category: "electronics",
    brand: "PulseFit",
    tags: ["fitness", "giftable"],
    price: 29.99,
    compareAt: 49.99,
    badge: "Choice",
    specs: [
      ["Display", '1.47" AMOLED always-on'],
      ["Battery", "14-day typical use"],
      ["Modes", "120+ sport modes, SpO2, stress"],
      ["Rating", "5ATM water resistant"],
    ],
  },
  {
    slug: "sample-keystrike-tkl",
    title: "KeyStrike TKL Mechanical Gaming Keyboard RGB Hot-Swappable",
    category: "electronics",
    brand: "KeyStrike",
    tags: ["gaming", "office"],
    price: 59.99,
    compareAt: 89.99,
    variants: [
      { name: "Red switches", stock: 11 },
      { name: "Brown switches", stock: 8 },
      { name: "Blue switches", stock: 6 },
    ],
    specs: [
      ["Layout", "87-key tenkeyless, aluminum frame"],
      ["Switches", "Hot-swappable linear/clicky options"],
      ["Lighting", "Per-key RGB, 19 effects"],
      ["Connection", "Wired USB-C + 2.4GHz + Bluetooth"],
    ],
  },
  {
    slug: "sample-razer-huntsman-v3",
    title: "Razer Huntsman V3 Pro Esports Analog Optical Gaming Keyboard",
    category: "electronics",
    brand: "Razer",
    tags: ["gaming", "streaming"],
    price: 219.99,
    compareAt: 249.99,
    specs: [
      ["Switches", "Analog optical Gen-2, Rapid Trigger"],
      ["Polling", "8000Hz HyperPolling"],
      ["Layout", "Full-size with media dial"],
      ["Lighting", "Chroma RGB per-key"],
    ],
  },
  {
    slug: "sample-netcore-wifi6-router",
    title: "NetCore Dual-Band WiFi 6 Router with Mesh Support AX3000",
    category: "electronics",
    brand: "NetCore",
    tags: ["networking", "offgrid", "home", "office"],
    price: 89.99,
    compareAt: 129.99,
    badge: "Hot",
    specs: [
      ["Standard", "WiFi 6 (802.11ax), AX3000"],
      ["Coverage", "Up to 2500 sq ft, mesh-ready"],
      ["Ports", "4x Gigabit LAN + 1x WAN"],
      ["Power", "12V/1.5A, works on 12V solar setups"],
    ],
  },
  {
    slug: "sample-netcore-gigabit-switch",
    title: "NetCore 5-Port Gigabit Ethernet Switch Plug-and-Play Metal",
    category: "electronics",
    brand: "NetCore",
    tags: ["networking", "offgrid", "office"],
    price: 16.49,
    compareAt: 24.99,
    specs: [
      ["Ports", "5x 10/100/1000Mbps auto-negotiation"],
      ["Housing", "Fanless metal, desktop/wall mount"],
      ["Power", "5V USB-C powered, 12V compatible"],
      ["Use", "Expand Starlink/router LAN ports"],
    ],
  },
  {
    slug: "sample-netcore-outdoor-cable-kit",
    title: "NetCore Outdoor Waterproof Ethernet Cable Kit 30M with Mounts",
    category: "electronics",
    brand: "NetCore",
    tags: ["networking", "offgrid", "outdoors"],
    price: 19.99,
    compareAt: 29.99,
    specs: [
      ["Cable", "30m Cat6, UV + waterproof jacket"],
      ["Speed", "Up to 10Gbps, 250MHz"],
      ["Includes", "20 wall mounts, 40 clips, coupler"],
      ["Use", "Run dish-to-router outdoors"],
    ],
  },
  {
    slug: "sample-voltpack-737-powerbank",
    title: "VoltPack 737 Power Bank 120W 24000mAh with Smart Display",
    category: "electronics",
    brand: "VoltPack",
    tags: ["power", "travel", "offgrid", "camping"],
    price: 74.99,
    compareAt: 109.99,
    specs: [
      ["Capacity", "24000mAh / 86Wh (flight-safe)"],
      ["Output", "120W 2-way fast charging, USB-C PD"],
      ["Display", "Smart screen with time-to-full"],
      ["Recharge", "Full in ~1h with 120W input"],
    ],
  },
  {
    slug: "sample-voltpack-solar-station",
    title: "VoltPack Portable Solar Power Station 300W with AC Outlets",
    category: "home",
    brand: "VoltPack",
    tags: ["offgrid", "camping", "power"],
    price: 189.99,
    compareAt: 299.99,
    badge: "Hot",
    trackStock: true,
    stock: 6,
    specs: [
      ["Capacity", "296Wh LiFePO4, 3000+ cycles"],
      ["Outputs", "2x AC 300W, 2x USB-C 100W, 12V car"],
      ["Solar", "200W max input, full in ~2h sun"],
      ["Use", "Runs routers, laptops, lights off-grid"],
    ],
  },
  {
    slug: "sample-volt regulatory-cam-4k",
    title: "VoltCam 4K Action Camera Waterproof with Dual Screen",
    category: "electronics",
    brand: "VoltCam",
    tags: ["outdoors", "travel", "vlogging"],
    price: 129.99,
    compareAt: 199.99,
    specs: [
      ["Video", "4K60, 2.7K120 slow-mo, HyperSmooth"],
      ["Screens", 'Front 1.4" + rear 2.27" touch'],
      ["Waterproof", "10m bare, 60m with case"],
      ["Battery", "2x 1720mAh removable"],
    ],
  },
  {
    slug: "sample-lumiglow-strip-10m",
    title: "LumiGlow LED Strip Lights 10M RGB Music Sync App Control",
    category: "electronics",
    brand: "LumiGlow",
    tags: ["gaming", "home-decor"],
    price: 16.99,
    compareAt: 29.99,
    badge: "Sale",
    specs: [
      ["Length", "10m (2x 5m), cuttable every 3 LEDs"],
      ["Control", "App + remote + voice (Alexa/Google)"],
      ["Modes", "Music sync, 16M colors, scenes"],
      ["Power", "USB 5V, TV/monitor backlight ready"],
    ],
  },
  {
    slug: "sample-dji-mini-4k-drone",
    title: "DJI Mini 4K Drone with 4K UHD Camera Under 249g",
    category: "electronics",
    brand: "DJI",
    tags: ["outdoors", "travel", "vlogging", "giftable"],
    price: 299.0,
    compareAt: 359.0,
    specs: [
      ["Camera", "4K/30fps, 3-axis gimbal"],
      ["Weight", "Under 249g (no FAA registration)"],
      ["Flight", "31-min max, 10km transmission"],
      ["Modes", "QuickShots, pano, auto return"],
    ],
  },
  // ----------------------------------------------------------------- phones
  {
    slug: "sample-iphone-15-128",
    title: "Apple iPhone 15 128GB Black Unlocked",
    category: "phones",
    brand: "Apple",
    tags: ["phones", "giftable"],
    price: 729.0,
    compareAt: 799.0,
    variants: [
      { name: "Black 128GB", stock: 5 },
      { name: "Blue 128GB", stock: 4 },
      { name: "Pink 256GB", price: 829.0, stock: 3 },
    ],
    specs: [
      ["Chip", "A16 Bionic"],
      ["Display", '6.1" Super Retina XDR, Dynamic Island'],
      ["Camera", "48MP main, 2x telephoto-quality zoom"],
      ["Connector", "USB-C, Face ID"],
    ],
  },
  {
    slug: "sample-galaxy-s24-128",
    title: "Samsung Galaxy S24 5G 128GB Onyx Black Unlocked",
    category: "phones",
    brand: "Samsung",
    tags: ["phones", "giftable"],
    price: 649.99,
    compareAt: 799.99,
    variants: [
      { name: "Onyx Black 128GB", stock: 6 },
      { name: "Marble Gray 256GB", price: 709.99, stock: 4 },
    ],
    specs: [
      ["Chip", "Snapdragon 8 Gen 3 for Galaxy"],
      ["Display", '6.2" AMOLED 120Hz, 2600 nits'],
      ["Camera", "50MP OIS triple, Galaxy AI photo tools"],
      ["Battery", "4000mAh, 25W fast charge"],
    ],
  },
  {
    slug: "sample-pixel-8a-128",
    title: "Google Pixel 8a 128GB Aloe Unlocked",
    category: "phones",
    brand: "Google",
    tags: ["phones", "giftable"],
    price: 399.0,
    compareAt: 499.0,
    badge: "Sale",
    specs: [
      ["Chip", "Google Tensor G3, 7 years updates"],
      ["Display", '6.1" Actua OLED 120Hz'],
      ["Camera", "64MP + Magic Editor, Best Take"],
      ["Battery", "24h+ adaptive, wireless charging"],
    ],
  },
  {
    slug: "sample-shieldcase-magsafe",
    title: "ShieldCase Magnetic Phone Case with Stand for iPhone and Samsung",
    category: "phones",
    brand: "ShieldCase",
    tags: ["phones", "protection"],
    price: 12.99,
    compareAt: 24.99,
    badge: "Choice",
    variants: [
      { name: "iPhone 15", stock: 22 },
      { name: "iPhone 14", stock: 18 },
      { name: "Galaxy S24", stock: 15 },
    ],
    specs: [
      ["Protection", "Military-grade 12ft drop tested"],
      ["Magnets", "N52 array, MagSafe + Qi2 compatible"],
      ["Stand", "Aluminum kickstand, portrait/landscape"],
      ["Finish", "Anti-yellow clear, grippy sides"],
    ],
  },
  {
    slug: "sample-apple-magsafe-charger",
    title: "Apple MagSafe Wireless Charger for iPhone and AirPods",
    category: "phones",
    brand: "Apple",
    tags: ["phones", "power"],
    price: 33.0,
    compareAt: 39.0,
    specs: [
      ["Output", "Up to 15W for iPhone 12 and later"],
      ["Alignment", "Magnetic snap, 1m USB-C cable"],
      ["Works with", "MagSafe cases, AirPods cases"],
    ],
  },
  {
    slug: "sample-voltpack-gan-65w",
    title: "VoltPack 65W GaN Fast Charger 3-Port USB-C Wall Adapter",
    category: "phones",
    brand: "VoltPack",
    tags: ["phones", "power", "travel"],
    price: 21.99,
    compareAt: 35.99,
    specs: [
      ["Output", "65W GaN II, 2x USB-C + USB-A"],
      ["Size", "45% smaller than stock bricks"],
      ["Safety", "Over-current/heat/voltage protection"],
      ["Use", "Charges laptop + phone together"],
    ],
  },
  {
    slug: "sample-shieldcase-tempered-3pk",
    title: "ShieldCase Tempered Glass Screen Protector 3-Pack with Alignment Tray",
    category: "phones",
    brand: "ShieldCase",
    tags: ["phones", "protection"],
    price: 7.99,
    compareAt: 14.99,
    specs: [
      ["Glass", "9H hardness, 0.33mm, case-friendly"],
      ["Coating", "Oleophobic anti-fingerprint"],
      ["Install", "Auto-alignment tray, dust-free kit"],
      ["Count", "3 protectors + camera lens covers"],
    ],
  },
  // ----------------------------------------------------------------- fashion
  {
    slug: "sample-nike-pegasus-41",
    title: "Nike Pegasus 41 Men's Road Running Shoes",
    category: "fashion",
    brand: "Nike",
    tags: ["running", "fitness", "giftable"],
    price: 109.99,
    compareAt: 140.0,
    variants: [
      { name: "US 9 Black", stock: 6 },
      { name: "US 10 Black", stock: 4 },
      { name: "US 10 White", stock: 5 },
      { name: "US 11 Blue", stock: 0 },
    ],
    specs: [
      ["Cushion", "React foam + forefoot Air Zoom"],
      ["Use", "Daily road running, neutral gait"],
      ["Upper", "Engineered mesh, reflective details"],
      ["Weight", "10.1 oz (men's 10)"],
    ],
  },
  {
    slug: "sample-adidas-ultraboost-5",
    title: "Adidas Ultraboost 5 Running Shoes Core Black",
    category: "fashion",
    brand: "Adidas",
    tags: ["running", "fitness"],
    price: 129.99,
    compareAt: 190.0,
    specs: [
      ["Cushion", "Boost midsole, Continental outsole"],
      ["Fit", "Primeknit+ adaptive upper"],
      ["Use", "Long daily miles, all surfaces"],
    ],
  },
  {
    slug: "sample-stridex-knit-runner",
    title: "StrideX Men's Lightweight Knit Running Sneakers",
    category: "fashion",
    brand: "StrideX",
    tags: ["running", "fitness", "giftable"],
    price: 39.99,
    compareAt: 65.0,
    badge: "Choice",
    variants: [
      { name: "Gray US 9", stock: 12 },
      { name: "Gray US 10", stock: 10 },
      { name: "Navy US 10", stock: 8 },
    ],
    specs: [
      ["Upper", "Breathable flyknit, sock-fit collar"],
      ["Sole", "EVA + rubber pods, machine washable"],
      ["Weight", "8.4 oz, true to size"],
    ],
  },
  {
    slug: "sample-bellamoda-maxi-dress",
    title: "BellaModa Women's Summer Floral Maxi Dress Beach Boho",
    category: "fashion",
    brand: "BellaModa",
    tags: ["summer", "beach", "giftable"],
    price: 32.99,
    compareAt: 58.0,
    variants: [
      { name: "Floral Blue S", stock: 7 },
      { name: "Floral Blue M", stock: 9 },
      { name: "Sunset L", stock: 5 },
    ],
    specs: [
      ["Fabric", "100% rayon, lined bodice"],
      ["Fit", "Smocked back, adjustable straps"],
      ["Care", "Machine wash cold"],
    ],
  },
  {
    slug: "sample-levis-trucker-jacket",
    title: "Levi's Men's Type III Sherpa Trucker Jacket",
    category: "fashion",
    brand: "Levi's",
    tags: ["fall", "giftable"],
    price: 98.0,
    compareAt: 148.0,
    specs: [
      ["Shell", "Cotton denim, sherpa lining"],
      ["Fit", "Regular, button front + flap pockets"],
      ["Care", "Machine wash"],
    ],
  },
  {
    slug: "sample-rayban-aviator",
    title: "Ray-Ban Aviator Classic Gold Frame Green G-15 Lenses",
    category: "fashion",
    brand: "Ray-Ban",
    tags: ["summer", "travel", "giftable"],
    price: 136.0,
    compareAt: 161.0,
    specs: [
      ["Lens", "G-15 green crystal, 100% UV"],
      ["Frame", "Gold metal, 58mm"],
      ["Includes", "Case + cleaning cloth"],
    ],
  },
  {
    slug: "sample-champion-hoodie",
    title: "Champion Men's Reverse Weave Pullover Hoodie",
    category: "fashion",
    brand: "Champion",
    tags: ["fall", "giftable"],
    price: 34.99,
    compareAt: 60.0,
    variants: [
      { name: "Black M", stock: 10 },
      { name: "Gray L", stock: 12 },
      { name: "Navy XL", stock: 6 },
    ],
    specs: [
      ["Fabric", "12oz heavyweight fleece, 82/18 cotton-poly"],
      ["Fit", "Classic, kangaroo pocket"],
      ["Care", "Machine wash, resists shrinkage"],
    ],
  },
  {
    slug: "sample-bellamoda-linen-shirt",
    title: "BellaModa Men's Linen Casual Button-Down Shirt",
    category: "fashion",
    brand: "BellaModa",
    tags: ["summer", "beach"],
    price: 27.99,
    compareAt: 45.0,
    specs: [
      ["Fabric", "55% linen / 45% cotton blend"],
      ["Fit", "Relaxed camp collar, coconut buttons"],
    ],
  },
  // -------------------------------------------------------------------- home
  {
    slug: "sample-nutrimix-blender-380",
    title: "NutriMix Portable Blender USB Rechargeable 380ml Fruit Juicer",
    category: "home",
    brand: "NutriMix",
    tags: ["kitchen", "fitness", "smoothies", "giftable"],
    price: 19.99,
    compareAt: 34.99,
    badge: "Choice",
    variants: [
      { name: "White", stock: 20 },
      { name: "Pink", stock: 14 },
      { name: "Mint", stock: 0 },
    ],
    specs: [
      ["Motor", "22,000 RPM, 6 stainless blades"],
      ["Battery", "4000mAh, 15 blends per charge, USB-C"],
      ["Use", "Crushes ice + frozen fruit, self-cleaning"],
    ],
  },
  {
    slug: "sample-cosori-airfryer-5qt",
    title: "Cosori Pro 5Qt Air Fryer with 9 Cooking Functions",
    category: "home",
    brand: "Cosori",
    tags: ["kitchen", "giftable"],
    price: 89.99,
    compareAt: 129.99,
    specs: [
      ["Capacity", "5Qt square basket, feeds 4-6"],
      ["Functions", "9 presets incl. bake, roast, reheat"],
      ["Temp", "170-400F, preheat + keep warm"],
      ["Care", "Dishwasher-safe nonstick basket"],
    ],
  },
  {
    slug: "sample-keurig-kmini",
    title: "Keurig K-Mini Single Serve Coffee Maker Black",
    category: "home",
    brand: "Keurig",
    tags: ["kitchen", "office", "giftable"],
    price: 69.99,
    compareAt: 99.99,
    specs: [
      ["Brews", "6-12oz K-Cup pods, strong button"],
      ["Size", "Under 5in wide, 1-cup reservoir"],
      ["Speed", "Coffee in minutes, auto-off"],
    ],
  },
  {
    slug: "sample-dyson-v12-slim",
    title: "Dyson V12 Detect Slim Cordless Vacuum with Laser Head",
    category: "home",
    brand: "Dyson",
    tags: ["home", "cleaning", "giftable"],
    price: 499.99,
    compareAt: 649.99,
    specs: [
      ["Suction", "150AW root-cyclone, laser dust reveal"],
      ["Run", "Up to 60 min, LCD particle count"],
      ["Bin", "Point-and-shoot hygienic emptying"],
      ["Heads", "Laser Slim Fluffy + Motorbar"],
    ],
  },
  {
    slug: "sample-tfal-cookware-12pc",
    title: "T-fal Signature 12-Piece Nonstick Cookware Set",
    category: "home",
    brand: "T-fal",
    tags: ["kitchen", "giftable"],
    price: 79.99,
    compareAt: 130.0,
    specs: [
      ["Pieces", "Fry pans, saucepans, Dutch oven, lids"],
      ["Coating", "ProGlide nonstick, Thermo-Spot heat ring"],
      ["Care", "Dishwasher safe, oven to 350F"],
    ],
  },
  {
    slug: "sample-hue-go-lamp",
    title: "Philips Hue Go Portable Smart Lamp White and Color",
    category: "home",
    brand: "Philips Hue",
    tags: ["home-decor", "gaming", "giftable"],
    price: 79.99,
    compareAt: 99.99,
    specs: [
      ["Light", "16M colors + warm-to-cool white"],
      ["Battery", "48h cordless glow, USB-C"],
      ["Control", "App, voice, Hue Bridge routines"],
    ],
  },
  {
    slug: "sample-fabricpro-lint-shaver",
    title: "FabricPro Electric Lint Remover Rechargeable Fabric Shaver",
    category: "home",
    brand: "FabricPro",
    tags: ["home", "laundry"],
    price: 11.99,
    compareAt: 19.99,
    specs: [
      ["Blades", "6-leaf stainless, 3-hole mesh"],
      ["Battery", "USB rechargeable, 60-min runtime"],
      ["Use", "Sweaters, sofas, bedding safe"],
    ],
  },
  {
    slug: "sample-sunglow-solar-string",
    title: "SunGlow Solar Outdoor String Lights 12M Waterproof Garden",
    category: "home",
    brand: "SunGlow",
    tags: ["offgrid", "outdoors", "garden", "camping"],
    price: 15.99,
    compareAt: 25.99,
    badge: "Sale",
    specs: [
      ["Length", "12m, 100 LED shatterproof bulbs"],
      ["Solar", "8h charge = 10h glow, auto dusk-on"],
      ["Modes", "8 lighting modes, IP65 waterproof"],
    ],
  },
  // ------------------------------------------------------------------ beauty
  {
    slug: "sample-glowlab-vitc-serum",
    title: "GlowLab Vitamin C Brightening Serum with Hyaluronic Acid 30ml",
    category: "beauty",
    brand: "GlowLab",
    tags: ["skincare", "giftable"],
    price: 12.99,
    compareAt: 24.99,
    badge: "Choice",
    specs: [
      ["Actives", "20% ethylated vitamin C + HA + vitamin E"],
      ["Targets", "Dark spots, dullness, fine lines"],
      ["Skin", "All types, fragrance-free, cruelty-free"],
    ],
  },
  {
    slug: "sample-cerave-moisturiser",
    title: "CeraVe Moisturising Cream Body and Face 454g",
    category: "beauty",
    brand: "CeraVe",
    tags: ["skincare"],
    price: 14.99,
    compareAt: 19.99,
    specs: [
      ["Actives", "3 essential ceramides + hyaluronic acid"],
      ["Tech", "MVE delivery, 48h hydration"],
      ["Skin", "Dry to very dry, fragrance-free"],
    ],
  },
  {
    slug: "sample-mac-matte-lipstick",
    title: "MAC Matte Lipstick Ruby Woo 3g",
    category: "beauty",
    brand: "MAC",
    tags: ["makeup", "giftable"],
    price: 19.0,
    compareAt: 23.0,
    variants: [
      { name: "Ruby Woo", stock: 9 },
      { name: "Velvet Teddy", stock: 7 },
      { name: "Mehr", stock: 6 },
    ],
    specs: [
      ["Finish", "Iconic matte, full coverage"],
      ["Wear", "8h, non-feathering"],
    ],
  },
  {
    slug: "sample-olaplex-no4-shampoo",
    title: "Olaplex No.4 Bond Maintenance Shampoo 250ml",
    category: "beauty",
    brand: "Olaplex",
    tags: ["haircare", "giftable"],
    price: 24.0,
    compareAt: 30.0,
    specs: [
      ["Tech", "Bis-aminopropyl bond builder"],
      ["For", "All hair, color-safe, sulfate-free"],
    ],
  },
  // ------------------------------------------------------------------ sports
  {
    slug: "sample-flexflow-yoga-mat",
    title: "FlexFlow Yoga Mat Non-Slip 6mm with Carry Strap",
    category: "sports",
    brand: "FlexFlow",
    tags: ["fitness", "yoga", "giftable"],
    price: 21.99,
    compareAt: 35.99,
    variants: [
      { name: "Teal 6mm", stock: 13 },
      { name: "Purple 6mm", stock: 11 },
      { name: "Gray 4mm travel", price: 18.99, stock: 9 },
    ],
    specs: [
      ["Size", '72" x 24", 6mm cushion, alignment lines'],
      ["Grip", "Dual-texture TPE, sweat-proof"],
      ["Includes", "Carry strap + storage bag"],
    ],
  },
  {
    slug: "sample-bowflex-552-dumbbell",
    title: "Bowflex SelectTech 552 Adjustable Dumbbell Single",
    category: "sports",
    brand: "Bowflex",
    tags: ["fitness", "home-gym", "giftable"],
    price: 149.0,
    compareAt: 199.0,
    specs: [
      ["Range", "5-52.5 lbs per hand, dial adjust"],
      ["Replaces", "15 sets of weights"],
      ["Space", "Compact, storage tray included"],
    ],
  },
  {
    slug: "sample-coleman-sundome-4p",
    title: "Coleman Sundome 4-Person Camping Tent",
    category: "sports",
    brand: "Coleman",
    tags: ["camping", "outdoors", "offgrid"],
    price: 99.99,
    compareAt: 139.99,
    specs: [
      ["Sleeps", "4, 9x7ft floor, 59in center"],
      ["Weather", "WeatherTec seams, rainfly, wind tested 35mph"],
      ["Setup", "10 minutes, pre-attached poles"],
    ],
  },
  {
    slug: "sample-trailpack-50l",
    title: "TrailPack Waterproof Hiking Backpack 50L with Rain Cover",
    category: "sports",
    brand: "TrailPack",
    tags: ["travel", "camping", "outdoors", "hiking"],
    price: 42.99,
    compareAt: 69.99,
    variants: [
      { name: "Forest Green", stock: 8 },
      { name: "Slate Gray", stock: 10 },
    ],
    specs: [
      ["Capacity", "50L + 10L extension collar"],
      ["Fit", "Ventilated back, hip belt, torso adjust"],
      ["Weather", "Rain cover included, water-repellent"],
    ],
  },
  {
    slug: "sample-hydroflask-32oz",
    title: "Hydro Flask 32oz Wide Mouth Water Bottle with Flex Cap",
    category: "sports",
    brand: "Hydro Flask",
    tags: ["fitness", "outdoors", "travel", "giftable"],
    price: 34.95,
    compareAt: 44.95,
    variants: [
      { name: "Pacific", stock: 16 },
      { name: "Black", stock: 20 },
      { name: "White", stock: 0 },
    ],
    specs: [
      ["Temp", "24h cold / 12h hot TempShield"],
      ["Steel", "18/8 pro-grade, BPA-free"],
      ["Fit", "Cupholder compatible, dishwasher safe"],
    ],
  },
  // -------------------------------------------------------------------- toys
  {
    slug: "sample-buildjoy-city-1200",
    title: "BuildJoy City Building Blocks Set 1200pcs STEM Educational",
    category: "toys",
    brand: "BuildJoy",
    tags: ["kids", "stem", "giftable"],
    price: 29.99,
    compareAt: 49.99,
    badge: "Choice",
    specs: [
      ["Pieces", "1200, major-brand compatible"],
      ["Builds", "25-in-1 guide: city, vehicles, robots"],
      ["Age", "6+, non-toxic ABS, storage box"],
    ],
  },
  {
    slug: "sample-catan-board-game",
    title: "Catan The Board Game Family Strategy (Base Game)",
    category: "toys",
    brand: "Catan Studio",
    tags: ["board-games", "family", "giftable"],
    price: 38.99,
    compareAt: 55.0,
    specs: [
      ["Players", "3-4 (expansions to 6), 60-120 min"],
      ["Age", "10+, trading + building strategy"],
      ["Includes", "19 hexes, cards, pieces, dice"],
    ],
  },
  {
    slug: "sample-ravensburger-puzzle-1000",
    title: "Ravensburger 1000 Piece Jigsaw Puzzle - Alpine Panorama",
    category: "toys",
    brand: "Ravensburger",
    tags: ["puzzles", "family", "giftable"],
    price: 19.99,
    compareAt: 26.99,
    specs: [
      ["Pieces", "1000 Softclick, 70x50cm finished"],
      ["Quality", "FSC cardboard, glare-free print"],
    ],
  },
  {
    slug: "sample-traxxas-rustler-rc",
    title: "Traxxas Rustler 2WD Stadium RC Truck with Battery and Charger",
    category: "toys",
    brand: "Traxxas",
    tags: ["rc", "outdoors", "giftable"],
    price: 189.95,
    compareAt: 219.95,
    trackStock: true,
    stock: 0,
    specs: [
      ["Speed", "35+ mph, Titan 12T 550 motor"],
      ["Ready", "RTR with 7-cell NiMH + charger"],
      ["Waterproof", "XL-5 ESC + sealed receiver"],
    ],
  },
  // -------------------------------------------------------------- automotive
  {
    slug: "sample-turbovac-handheld-120w",
    title: "TurboVac Car Vacuum Portable Wireless Handheld 120W",
    category: "automotive",
    brand: "TurboVac",
    tags: ["automotive", "cleaning"],
    price: 32.99,
    compareAt: 59.99,
    specs: [
      ["Suction", "120W brushless, 16kPa, HEPA"],
      ["Battery", "7800mAh, 30-min runtime, USB-C car charge"],
      ["Kit", "Crevice, brush, hose + storage bag"],
    ],
  },
  {
    slug: "sample-nextbase-322gw-dashcam",
    title: "Nextbase 322GW Dash Cam with Alexa and Emergency SOS",
    category: "automotive",
    brand: "Nextbase",
    tags: ["automotive", "travel"],
    price: 149.99,
    compareAt: 199.99,
    specs: [
      ["Video", "1080p HD, 140-degree lens, night vision"],
      ["Features", "Alexa built-in, Emergency SOS, parking mode"],
      ["Mount", "Click&Go magnetic, iOS/Android app"],
    ],
  },
  {
    slug: "sample-noco-gb40-jumpstarter",
    title: "NOCO Boost Plus GB40 1000A Jump Starter and Power Bank",
    category: "automotive",
    brand: "NOCO",
    tags: ["automotive", "power", "emergency"],
    price: 79.95,
    compareAt: 99.95,
    badge: "Hot",
    specs: [
      ["Power", "1000A, gas to 6L / diesel to 3L"],
      ["Safety", "Spark-proof + reverse polarity protection"],
      ["Extras", "100-lumen flashlight, USB power bank"],
    ],
  },
  {
    slug: "sample-turbovac-tire-inflator",
    title: "TurboVac Cordless Tire Inflator with Digital Gauge 150PSI",
    category: "automotive",
    brand: "TurboVac",
    tags: ["automotive", "emergency"],
    price: 35.99,
    compareAt: 55.99,
    specs: [
      ["Pressure", "150PSI max, auto-stop at target"],
      ["Battery", "6000mAh USB-C, inflates 4 tires/charge"],
      ["Extras", "LED light, ball + bike adapters"],
    ],
  },
  // ---------------------------------------------------------- batch 2: depth
  {
    slug: "sample-logitech-c920-webcam",
    title: "Logitech C920S HD Pro Webcam with Privacy Shutter",
    category: "electronics",
    brand: "Logitech",
    tags: ["office", "streaming", "giftable"],
    price: 59.99,
    compareAt: 79.99,
    specs: [
      ["Video", "1080p/30fps, autofocus, light correction"],
      ["Audio", "Dual stereo mics with noise reduction"],
      ["Mount", "Universal clip + tripod thread, privacy shutter"],
    ],
  },
  {
    slug: "sample-samsung-t7-shield-1tb",
    title: "Samsung T7 Shield 1TB Portable SSD USB 3.2",
    category: "electronics",
    brand: "Samsung",
    tags: ["office", "travel", "giftable"],
    price: 89.99,
    compareAt: 139.99,
    specs: [
      ["Speed", "Up to 1050/1000 MB/s read/write"],
      ["Rugged", "IP65 dust/water + 3m drop resistant"],
      ["Use", "USB-C/A compatible, 256-bit encryption"],
    ],
  },
  {
    slug: "sample-anker-737-gan-120w",
    title: "Anker 737 GaNPrime 120W 3-Port Fast Charger",
    category: "electronics",
    brand: "Anker",
    tags: ["power", "travel", "office"],
    price: 64.99,
    compareAt: 94.99,
    specs: [
      ["Output", "120W max, 2x USB-C + USB-A"],
      ["Tech", "GaNPrime, ActiveShield temp monitoring"],
      ["Size", "Compact foldable-prong design"],
    ],
  },
  {
    slug: "sample-pixel-buds-pro-2",
    title: "Google Pixel Buds Pro 2 with Active Noise Cancellation",
    category: "phones",
    brand: "Google",
    tags: ["audio", "phones", "giftable"],
    price: 179.0,
    compareAt: 229.0,
    specs: [
      ["Chip", "Tensor A1, Silent Seal 2.0 ANC"],
      ["Battery", "8h buds, 30h case, wireless charging"],
      ["Features", "Gemini hands-free, multipoint, IPX4"],
    ],
  },
  {
    slug: "sample-voltpack-car-mount-magsafe",
    title: "VoltPack Magnetic Car Phone Mount with Suction and Vent Clips",
    category: "phones",
    brand: "VoltPack",
    tags: ["phones", "automotive", "travel"],
    price: 15.99,
    compareAt: 25.99,
    specs: [
      ["Hold", "N52 magnets, one-hand dock"],
      ["Mount", "Suction windshield + vent clip included"],
      ["Works with", "MagSafe + magnetic cases"],
    ],
  },
  {
    slug: "sample-adidas-samba-adv",
    title: "Adidas Samba ADV Unisex Sneakers White Gum",
    category: "fashion",
    brand: "Adidas",
    tags: ["streetwear", "giftable"],
    price: 90.0,
    compareAt: 100.0,
    variants: [
      { name: "US 8", stock: 5 },
      { name: "US 9", stock: 7 },
      { name: "US 10", stock: 6 },
    ],
    specs: [
      ["Upper", "Full-grain leather, suede T-toe"],
      ["Sole", "Gum rubber cupsole"],
      ["Fit", "True to size, skate-ready cushion"],
    ],
  },
  {
    slug: "sample-bellamoda-satin-skirt",
    title: "BellaModa Satin Midi Skirt with Elastic Waist",
    category: "fashion",
    brand: "BellaModa",
    tags: ["summer", "giftable"],
    price: 24.99,
    compareAt: 42.0,
    variants: [
      { name: "Champagne S", stock: 6 },
      { name: "Black M", stock: 8 },
    ],
    specs: [
      ["Fabric", "Matte satin, midi length, lined"],
      ["Fit", "Elastic back waist, side slit"],
    ],
  },
  {
    slug: "sample-nike-dri-fit-tee",
    title: "Nike Dri-FIT Men's Training T-Shirt 2-Pack",
    category: "fashion",
    brand: "Nike",
    tags: ["fitness", "running", "giftable"],
    price: 32.0,
    compareAt: 45.0,
    variants: [
      { name: "Black M", stock: 15 },
      { name: "Gray L", stock: 12 },
    ],
    specs: [
      ["Fabric", "Dri-FIT sweat-wicking knit"],
      ["Fit", "Standard training cut, 2-pack"],
    ],
  },
  {
    slug: "sample-brooklinen-luxe-core-set",
    title: "Brooklinen Luxe Core Sheet Set 100% Long-Staple Cotton",
    category: "home",
    brand: "Brooklinen",
    tags: ["home", "bedroom", "giftable"],
    price: 159.0,
    compareAt: 199.0,
    variants: [
      { name: "White Queen", stock: 9 },
      { name: "Slate Queen", stock: 7 },
      { name: "White King", price: 179.0, stock: 6 },
    ],
    specs: [
      ["Fabric", "480TC long-staple cotton sateen"],
      ["Set", "Fitted, flat, 2 pillowcases"],
      ["Care", "Gets softer with every wash"],
    ],
  },
  {
    slug: "sample-levoit-humidifier-6l",
    title: "Levoit 6L Top-Fill Humidifier with Smart App and Aroma Box",
    category: "home",
    brand: "Levoit",
    tags: ["home", "wellness"],
    price: 69.99,
    compareAt: 99.99,
    specs: [
      ["Tank", "6L top-fill, 60h runtime low mist"],
      ["Control", "App + Alexa voice, auto humidity mode"],
      ["Care", "Aroma pad tray, dishwasher-safe tank"],
    ],
  },
  {
    slug: "sample-iris-storage-3pk",
    title: "IRIS USA 19Qt Stackable Storage Bins with Lids 3-Pack",
    category: "home",
    brand: "IRIS USA",
    tags: ["home", "organization"],
    price: 29.99,
    compareAt: 42.99,
    specs: [
      ["Size", "19Qt each, latch lids, stackable"],
      ["Material", "BPA-free, see-through walls"],
    ],
  },
  {
    slug: "sample-laroche-sunscreen-50",
    title: "La Roche-Posay Anthelios SPF 50 Ultra-Light Sunscreen 50ml",
    category: "beauty",
    brand: "La Roche-Posay",
    tags: ["skincare", "summer", "giftable"],
    price: 19.99,
    compareAt: 23.99,
    specs: [
      ["SPF", "50, UVA/UVB, oxybenzone-free"],
      ["Finish", "Fast-absorbing, no white cast"],
      ["Skin", "All types incl. sensitive"],
    ],
  },
  {
    slug: "sample-maison-lumiere-parfum",
    title: "Maison Lumiere Citrus Bloom Eau de Parfum 50ml",
    category: "beauty",
    brand: "Maison Lumiere",
    tags: ["fragrance", "giftable"],
    price: 42.0,
    compareAt: 58.0,
    specs: [
      ["Notes", "Bergamot, neroli, white musk"],
      ["Wear", "6-8h, unisex everyday scent"],
    ],
  },
  {
    slug: "sample-dyson-supersonic-hd15",
    title: "Dyson Supersonic HD15 Hair Dryer with Flyaway Smoother",
    category: "beauty",
    brand: "Dyson",
    tags: ["haircare", "giftable"],
    price: 329.99,
    compareAt: 429.99,
    specs: [
      ["Motor", "V9 digital, intelligent heat control"],
      ["Attachments", "5 styling heads incl. flyaway smoother"],
      ["Speed", "Fast drying, no extreme heat damage"],
    ],
  },
  {
    slug: "sample-trx-bands-pro",
    title: "TRX Pro Resistance Bands Set with Handles and Door Anchor",
    category: "sports",
    brand: "TRX",
    tags: ["fitness", "home-gym", "travel"],
    price: 45.99,
    compareAt: 69.99,
    specs: [
      ["Levels", "5 stackable bands, 10-150 lbs combined"],
      ["Kit", "Handles, ankle straps, door anchor, bag"],
    ],
  },
  {
    slug: "sample-triggerpoint-roller",
    title: "TriggerPoint GRID Foam Roller 13-Inch for Recovery",
    category: "sports",
    brand: "TriggerPoint",
    tags: ["fitness", "recovery", "running"],
    price: 27.99,
    compareAt: 36.99,
    specs: [
      ["Design", "Multi-density GRID pattern, 500lb limit"],
      ["Size", '13" x 5.5", sweat-proof EVA'],
    ],
  },
  {
    slug: "sample-kryptonite-evolution-lock",
    title: "Kryptonite Evolution Mini-7 Bike U-Lock with Cable",
    category: "sports",
    brand: "Kryptonite",
    tags: ["cycling", "travel", "commuting"],
    price: 62.99,
    compareAt: 79.99,
    specs: [
      ["Security", "13mm hardened shackle, 7/10 rating"],
      ["Includes", "4ft cable + frame mount"],
    ],
  },
  {
    slug: "sample-nerf-elite-2pack",
    title: "Nerf Elite Foam Blaster 2-Pack with 40 Darts",
    category: "toys",
    brand: "Nerf",
    tags: ["kids", "outdoors", "giftable"],
    price: 24.99,
    compareAt: 34.99,
    specs: [
      ["Range", "Up to 90ft, pump action"],
      ["Includes", "2 blasters + 40 elite darts"],
      ["Age", "8+"],
    ],
  },
  {
    slug: "sample-barbie-dreamhouse-mini",
    title: "Barbie Mini Dreamhouse Playset with Furniture",
    category: "toys",
    brand: "Barbie",
    tags: ["kids", "giftable"],
    price: 39.99,
    compareAt: 49.99,
    specs: [
      ["Size", "3 floors, 360 play, folds shut"],
      ["Includes", "House + furniture pieces"],
      ["Dolls", "Works with mini dolls (sold separately)"],
    ],
  },
  {
    slug: "sample-meguiars-wash-kit",
    title: "Meguiar's Complete Car Wash Kit with Wash, Wax and Microfiber",
    category: "automotive",
    brand: "Meguiar's",
    tags: ["automotive", "cleaning", "giftable"],
    price: 29.99,
    compareAt: 44.99,
    specs: [
      ["Includes", "Wash + wax, wheel cleaner, 3 towels, mitt"],
      ["Paint", "Clear-coat safe, pH balanced"],
    ],
  },
  {
    slug: "sample-weathertech-mats-set",
    title: "WeatherTech Custom FloorLiner Set Front Row Black",
    category: "automotive",
    brand: "WeatherTech",
    tags: ["automotive"],
    price: 129.95,
    compareAt: 149.95,
    specs: [
      ["Fit", "Laser-measured, vehicle-specific"],
      ["Material", "Odorless TPE, channels trap water"],
    ],
  },
];
