-- Split fulfilment: one Shipment (parcel) per store per order, plus a
-- first-class Returns/RMA flow.
--
-- HAND-WRITTEN, not generated by `prisma migrate diff`. Two reasons:
--
--  1. "Product"."search" is a GENERATED ALWAYS AS ... STORED tsvector created
--     by the search_fts migration, backing a GIN index that the search engine
--     ranks against. Prisma cannot model generated columns, so a generated
--     migration drops the column and its indexes — silently disabling
--     full-text search. Those statements are deliberately omitted here.
--
--  2. Tracking columns are dropped from "Order" below, so existing rows have to
--     be backfilled into "Shipment" first.

-- CreateEnum
CREATE TYPE "ShipmentStatus" AS ENUM ('PENDING', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "ReturnStatus" AS ENUM ('REQUESTED', 'ACCEPTED', 'RECEIVED', 'REFUNDED', 'REJECTED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ReturnReason" AS ENUM ('NOT_AS_DESCRIBED', 'DEFECTIVE', 'WRONG_ITEM', 'NO_LONGER_NEEDED', 'BETTER_PRICE_ELSEWHERE', 'DAMAGED_IN_TRANSIT', 'OTHER');

-- CreateTable
CREATE TABLE "Shipment" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "status" "ShipmentStatus" NOT NULL DEFAULT 'PENDING',
    "shippingCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "carrier" TEXT,
    "trackingNumber" TEXT,
    "shippedAt" TIMESTAMP(3),
    "deliveredAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Shipment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReturnRequest" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "buyerId" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "shipmentId" TEXT,
    "status" "ReturnStatus" NOT NULL DEFAULT 'REQUESTED',
    "reason" "ReturnReason" NOT NULL,
    "note" TEXT,
    "items" JSONB NOT NULL,
    "refundAmount" DECIMAL(10,2),
    "sellerNote" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReturnRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReturnMessage" (
    "id" TEXT NOT NULL,
    "returnId" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "authorId" TEXT,
    "body" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ReturnMessage_pkey" PRIMARY KEY ("id")
);

-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN "shipmentId" TEXT;

-- ----------------------------------------------------------------------------
-- Backfill: one shipment per (order, store), carrying the order's tracking.
-- ----------------------------------------------------------------------------

-- Shipping cost is split across stores in proportion to each store's share of
-- the order subtotal, so the shipment costs always sum back to Order.shipping.
WITH line_totals AS (
    SELECT
        oi."orderId",
        oi."storeId",
        SUM(oi."price" * oi."qty") AS store_total,
        SUM(SUM(oi."price" * oi."qty")) OVER (PARTITION BY oi."orderId") AS order_total
    FROM "OrderItem" oi
    GROUP BY oi."orderId", oi."storeId"
),
order_totals AS (
    SELECT id, shipping FROM "Order"
)
INSERT INTO "Shipment" (
    "id", "orderId", "storeId", "status", "shippingCost",
    "carrier", "trackingNumber", "shippedAt", "deliveredAt",
    "createdAt", "updatedAt"
)
SELECT
    md5(ot.id || lt."storeId" || 'shipment') AS id,
    ot.id,
    lt."storeId",
    CASE ot.status
        WHEN 'SHIPPED'   THEN 'IN_TRANSIT'::"ShipmentStatus"
        WHEN 'DELIVERED' THEN 'DELIVERED'::"ShipmentStatus"
        WHEN 'CANCELLED' THEN 'CANCELLED'::"ShipmentStatus"
        WHEN 'REFUNDED'  THEN 'REFUNDED'::"ShipmentStatus"
        ELSE 'PENDING'::"ShipmentStatus"
    END,
    CASE
        WHEN lt.order_total > 0 THEN ROUND(ot2.shipping * (lt.store_total / lt.order_total), 2)
        ELSE ot2.shipping
    END,
    ot.carrier,
    ot."trackingNumber",
    ot."shippedAt",
    ot."deliveredAt",
    ot."createdAt",
    now()
FROM line_totals lt
JOIN "Order" ot   ON ot.id = lt."orderId"
JOIN order_totals ot2 ON ot2.id = lt."orderId";

-- Attach each order line to its store's parcel.
UPDATE "OrderItem" oi
SET "shipmentId" = s."id"
FROM "Shipment" s
WHERE s."orderId" = oi."orderId" AND s."storeId" = oi."storeId";

-- Drop the now-derived order-level tracking columns.
ALTER TABLE "Order" DROP COLUMN "carrier",
DROP COLUMN "deliveredAt",
DROP COLUMN "shippedAt",
DROP COLUMN "trackingNumber";

-- CreateIndex
CREATE INDEX "Shipment_storeId_status_idx" ON "Shipment"("storeId", "status");
CREATE INDEX "Shipment_status_createdAt_idx" ON "Shipment"("status", "createdAt");
CREATE UNIQUE INDEX "Shipment_orderId_storeId_key" ON "Shipment"("orderId", "storeId");
CREATE INDEX "ReturnRequest_orderId_idx" ON "ReturnRequest"("orderId");
CREATE INDEX "ReturnRequest_storeId_status_idx" ON "ReturnRequest"("storeId", "status");
CREATE INDEX "ReturnRequest_buyerId_createdAt_idx" ON "ReturnRequest"("buyerId", "createdAt");
CREATE INDEX "OrderItem_shipmentId_idx" ON "OrderItem"("shipmentId");
CREATE INDEX "OrderItem_storeId_idx" ON "OrderItem"("storeId");

-- AddForeignKey
ALTER TABLE "Shipment" ADD CONSTRAINT "Shipment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Shipment" ADD CONSTRAINT "Shipment_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ReturnRequest" ADD CONSTRAINT "ReturnRequest_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ReturnRequest" ADD CONSTRAINT "ReturnRequest_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ReturnRequest" ADD CONSTRAINT "ReturnRequest_buyerId_fkey" FOREIGN KEY ("buyerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReturnRequest" ADD CONSTRAINT "ReturnRequest_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReturnMessage" ADD CONSTRAINT "ReturnMessage_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "ReturnRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
